[package]
name = "abc_util"
version = "0.1.0"
authors = ["Shunsuke Mie <sux2mfgj@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
openssl-probe = "0.1.2"
reqwest = "*"
scraper = "*"
clap = {version = "2.33", features = ["yaml"]}
shrust = "0.0.6"
